# goX — RADIUS istemcileri (NAS).
# Cihazlar WireGuard tüneli üzerinden bağlanır (10.88.0.0/24). Şimdilik ortak secret;
# ileride cihaz başına secret'a geçilecek.

client localhost {
	ipaddr = 127.0.0.1
	secret = testing123
}

client docker_net {
	ipaddr = 172.16.0.0/12
	secret = goxradius
}

client tunnel {
	ipaddr = 10.88.0.0/24
	secret = goxradius
}
